# Generated by Django 6.0.5 on 2026-05-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('foodie', 'Foodie'), ('chef', 'Chef')], default='foodie', max_length=10),
        ),
    ]
