# Generated by Django 5.2.7 on 2025-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('chef', 'Chef')], default='user', max_length=10),
        ),
    ]
